### ISSUE TITLE
Interchain token transfer between EVM and Cosmos testnets using Axelarjs-SDK is not working

### ISSUE THREAD

**Issue by Adw8** [axelarnetwork/axelarjs-sdk#320]
I'm trying to perform a cross chain token transfer between testnets, following the [Axelar docs](https://docs.axelar.dev/dev/send-tokens/introduction#send-tokens-cross-chain). 

I have tried token transfers between the following testnets:
- Avalanche to Osmosis
- Arbitrum to Osmosis
- Sepolia to Osmosis

However, I am running in the following issues:

#### 1. `Error: cannot estimate gas; transaction may fail or may require manual gas limit`
Steps to reproduce
- Have USDC and AVAX tokens in your wallet
- Add your wallet's private key to the `.env` file
- Setup Node.js environment with Axelarjs dependancies
- Run the following code
```
import { AxelarAssetTransfer, CHAINS, Environment, SendTokenParams } from "@axelar-network/axelarjs-sdk";
import { ethers, Wallet } from "ethers";

const api = new AxelarAssetTransfer({ environment: Environment.TESTNET });

const getSigner = () => {
  const privateKey = PRIVATE_KEY;
  return new Wallet(privateKey);
};


async function test() {
  const provider = new ethers.providers.JsonRpcProvider(
    "https://api.avax-test.network/ext/bc/C/rpc"
  );
  const signer = getSigner().connect(provider);
  const requestOptions = {
    fromChain: CHAINS.TESTNET.AVALANCHE,
    toChain: CHAINS.TESTNET.OSMOSIS,
    destinationAddress: [your osmosis address],
    asset: { symbol: "aUSDC" },
    amountInAtomicUnits: "5000000",
    options: {
      evmOptions: {
        signer,
        provider,
        txOptions: null,
        approveSendForMe: true,
      },
    },
  };
  return api.sendToken(requestOptions);
}
test().then((transaction) => {
  console.log(transaction); // Print the transaction
});
```
On running the above code, I am getting the following error:
```
adwait@vivobook-m1603qa:~/projects/axelar/axelar-experiments$ node evmTransfer.js 
/home/adwait/projects/axelar/axelar-experiments/node_modules/@ethersproject/logger/lib/index.js:238
        var error = new Error(message);

<ref *1> Error: cannot estimate gas; transaction may fail or may require manual gas limit [ See: https://links.ethers.org/v5-errors-UNPREDICTABLE_GAS_LIMIT ] (error={"reason":"execution reverted","code":"UNPREDICTABLE_GAS_LIMIT","method":"estimateGas","transaction":{"from":"0x873784c8A011A32C7635C8d8D3D2c83060532A49","maxPriorityFeePerGas":{"type":"BigNumber","hex":"0x59682f00"},"maxFeePerGas":{"type":"BigNumber","hex":"0x0bfda3a300"},"to":"0xC249632c2D40b9001FE907806902f63038B737Ab","data":"0x26ef699d000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000c0000000000000000000000000000000000000000000000000000000000000012000000000000000000000000000000000000000000000000000000000004c4b4000000000000000000000000000000000000000000000000000000000000000096f736d6f7369732d370000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002b6f736d6f31657539796c383776346537326473636c32353635706e666e646577356a363865367a3965323400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000067561757364630000000000000000000000000000000000000000000000000000","type":2,"accessList":null},"error":{"reason":"processing response error","code":"SERVER_ERROR","body":"{\"jsonrpc\":\"2.0\",\"id\":76,\"error\":{\"code\":3,\"message\":\"execution reverted\",\"data\":\"0x72ba137e000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000067561757364630000000000000000000000000000000000000000000000000000\"}}","error":{"code":3,"data":"0x72ba137e000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000067561757364630000000000000000000000000000000000000000000000000000"},"requestBody":"{\"method\":\"eth_estimateGas\",\"params\":[{\"type\":\"0x2\",\"maxFeePerGas\":\"0xbfda3a300\",\"maxPriorityFeePerGas\":\"0x59682f00\",\"from\":\"0x873784c8a011a32c7635c8d8d3d2c83060532a49\",\"to\":\"0xc249632c2d40b9001fe907806902f63038b737ab\",\"data\":\"0x26ef699d000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000c0000000000000000000000000000000000000000000000000000000000000012000000000000000000000000000000000000000000000000000000000004c4b4000000000000000000000000000000000000000000000000000000000000000096f736d6f7369732d370000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002b6f736d6f31657539796c383776346537326473636c32353635706e666e646577356a363865367a3965323400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000067561757364630000000000000000000000000000000000000000000000000000\"}],\"id\":76,\"jsonrpc\":\"2.0\"}","requestMethod":"POST","url":"https://api.avax-test.network/ext/bc/C/rpc"}}, tx={"to":{},"data":"0x26ef699d000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000c0000000000000000000000000000000000000000000000000000000000000012000000000000000000000000000000000000000000000000000000000004c4b4000000000000000000000000000000000000000000000000000000000000000096f736d6f7369732d370000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002b6f736d6f31657539796c383776346537326473636c32353635706e666e646577356a363865367a3965323400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000067561757364630000000000000000000000000000000000000000000000000000","from":"0x873784c8A011A32C7635C8d8D3D2c83060532A49","type":2,"maxFeePerGas":{"type":"BigNumber","hex":"0x0bfda3a300"},"maxPriorityFeePerGas":{"type":"BigNumber","hex":"0x59682f00"},"nonce":{},"gasLimit":{},"chainId":{}}, code=UNPREDICTABLE_GAS_LIMIT, version=abstract-signer/5.7.0)
    at Logger.makeError (/home/adwait/projects/axelar/axelar-experiments/node_modules/@ethersproject/logger/lib/index.js:238:21)
    at Logger.throwError (/home/adwait/projects/axelar/axelar-experiments/node_modules/@ethersproject/logger/lib/index.js:247:20)
    at /home/adwait/projects/axelar/axelar-experiments/node_modules/@ethersproject/abstract-signer/lib/index.js:365:47
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 8) {
  reason: 'cannot estimate gas; transaction may fail or may require manual gas limit',
  code: 'UNPREDICTABLE_GAS_LIMIT',
  error: Error: cannot estimate gas; transaction may fail or may require manual gas limit [ See: https://links.ethers.org/v5-errors-UNPREDICTABLE_GAS_LIMIT ] (reason="execution reverted", method="estimateGas", transaction={"from":"0x873784c8A011A32C7635C8d8D3D2c83060532A49","maxPriorityFeePerGas":{"type":"BigNumber","hex":"0x59682f00"},"maxFeePerGas":{"type":"BigNumber","hex":"0x0bfda3a300"},"to":"0xC249632c2D40b9001FE907806902f63038B737Ab","data":"0x26ef699d000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000c0000000000000000000000000000000000000000000000000000000000000012000000000000000000000000000000000000000000000000000000000004c4b4000000000000000000000000000000000000000000000000000000000000000096f736d6f7369732d370000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002b6f736d6f31657539796c383776346537326473636c32353635706e666e646577356a363865367a3965323400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000067561757364630000000000000000000000000000000000000000000000000000","type":2,"accessList":null}, error={"reason":"processing response error","code":"SERVER_ERROR","body":"{\"jsonrpc\":\"2.0\",\"id\":76,\"error\":{\"code\":3,\"message\":\"execution reverted\",\"data\":\"0x72ba137e000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000067561757364630000000000000000000000000000000000000000000000000000\"}}","error":{"code":3,"data":"0x72ba137e000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000067561757364630000000000000000000000000000000000000000000000000000"},"requestBody":"{\"method\":\"eth_estimateGas\",\"params\":[{\"type\":\"0x2\",\"maxFeePerGas\":\"0xbfda3a300\",\"maxPriorityFeePerGas\":\"0x59682f00\",\"from\":\"0x873784c8a011a32c7635c8d8d3d2c83060532a49\",\"to\":\"0xc249632c2d40b9001fe907806902f63038b737ab\",\"data\":\"0x26ef699d000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000c0000000000000000000000000000000000000000000000000000000000000012000000000000000000000000000000000000000000000000000000000004c4b4000000000000000000000000000000000000000000000000000000000000000096f736d6f7369732d370000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002b6f736d6f31657539796c383776346537326473636c32353635706e666e646577356a363865367a3965323400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000067561757364630000000000000000000000000000000000000000000000000000\"}],\"id\":76,\"jsonrpc\":\"2.0\"}","requestMethod":"POST","url":"https://api.avax-test.network/ext/bc/C/rpc"}, code=UNPREDICTABLE_GAS_LIMIT, version=providers/5.7.2)
      at Logger.makeError (/home/adwait/projects/axelar/axelar-experiments/node_modules/@ethersproject/logger/lib/index.js:238:21)
      at Logger.throwError (/home/adwait/projects/axelar/axelar-experiments/node_modules/@ethersproject/logger/lib/index.js:247:20)
      at checkError (/home/adwait/projects/axelar/axelar-experiments/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:122:20)
      at JsonRpcProvider.<anonymous> (/home/adwait/projects/axelar/axelar-experiments/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:751:47)
      at step (/home/adwait/projects/axelar/axelar-experiments/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:48:23)
      at Object.throw (/home/adwait/projects/axelar/axelar-experiments/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:29:53)
      at rejected (/home/adwait/projects/axelar/axelar-experiments/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:21:65)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
    reason: 'execution reverted',
    code: 'UNPREDICTABLE_GAS_LIMIT',
    method: 'estimateGas',
    transaction: {
      from: '0x873784c8A011A32C7635C8d8D3D2c83060532A49',
      maxPriorityFeePerGas: BigNumber { _hex: '0x59682f00', _isBigNumber: true },
      maxFeePerGas: BigNumber { _hex: '0x0bfda3a300', _isBigNumber: true },
      to: '0xC249632c2D40b9001FE907806902f63038B737Ab',
      data: '0x26ef699d000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000c0000000000000000000000000000000000000000000000000000000000000012000000000000000000000000000000000000000000000000000000000004c4b4000000000000000000000000000000000000000000000000000000000000000096f736d6f7369732d370000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002b6f736d6f31657539796c383776346537326473636c32353635706e666e646577356a363865367a3965323400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000067561757364630000000000000000000000000000000000000000000000000000',
      type: 2,
      accessList: null
    },
    error: Error: processing response error (body="{\"jsonrpc\":\"2.0\",\"id\":76,\"error\":{\"code\":3,\"message\":\"execution reverted\",\"data\":\"0x72ba137e000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000067561757364630000000000000000000000000000000000000000000000000000\"}}", error={"code":3,"data":"0x72ba137e000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000067561757364630000000000000000000000000000000000000000000000000000"}, requestBody="{\"method\":\"eth_estimateGas\",\"params\":[{\"type\":\"0x2\",\"maxFeePerGas\":\"0xbfda3a300\",\"maxPriorityFeePerGas\":\"0x59682f00\",\"from\":\"0x873784c8a011a32c7635c8d8d3d2c83060532a49\",\"to\":\"0xc249632c2d40b9001fe907806902f63038b737ab\",\"data\":\"0x26ef699d000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000c0000000000000000000000000000000000000000000000000000000000000012000000000000000000000000000000000000000000000000000000000004c4b4000000000000000000000000000000000000000000000000000000000000000096f736d6f7369732d370000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002b6f736d6f31657539796c383776346537326473636c32353635706e666e646577356a363865367a3965323400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000067561757364630000000000000000000000000000000000000000000000000000\"}],\"id\":76,\"jsonrpc\":\"2.0\"}", requestMethod="POST", url="https://api.avax-test.network/ext/bc/C/rpc", code=SERVER_ERROR, version=web/5.7.1)
        at Logger.makeError (/home/adwait/projects/axelar/axelar-experiments/node_modules/@ethersproject/logger/lib/index.js:238:21)
        at Logger.throwError (/home/adwait/projects/axelar/axelar-experiments/node_modules/@ethersproject/logger/lib/index.js:247:20)
        at /home/adwait/projects/axelar/axelar-experiments/node_modules/@ethersproject/web/lib/index.js:313:32
        at step (/home/adwait/projects/axelar/axelar-experiments/node_modules/@ethersproject/web/lib/index.js:33:23)
        at Object.next (/home/adwait/projects/axelar/axelar-experiments/node_modules/@ethersproject/web/lib/index.js:14:53)
        at fulfilled (/home/adwait/projects/axelar/axelar-experiments/node_modules/@ethersproject/web/lib/index.js:5:58)
        at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
      reason: 'processing response error',
      code: 'SERVER_ERROR',
      body: '{"jsonrpc":"2.0","id":76,"error":{"code":3,"message":"execution reverted","data":"0x72ba137e000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000067561757364630000000000000000000000000000000000000000000000000000"}}',
      error: Error: execution reverted
          at getResult (/home/adwait/projects/axelar/axelar-experiments/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:191:21)
          at processJsonFunc (/home/adwait/projects/axelar/axelar-experiments/node_modules/@ethersproject/web/lib/index.js:356:22)
          at /home/adwait/projects/axelar/axelar-experiments/node_modules/@ethersproject/web/lib/index.js:288:46
          at step (/home/adwait/projects/axelar/axelar-experiments/node_modules/@ethersproject/web/lib/index.js:33:23)
          at Object.next (/home/adwait/projects/axelar/axelar-experiments/node_modules/@ethersproject/web/lib/index.js:14:53)
          at fulfilled (/home/adwait/projects/axelar/axelar-experiments/node_modules/@ethersproject/web/lib/index.js:5:58)
          at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
        code: 3,
        data: '0x72ba137e000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000067561757364630000000000000000000000000000000000000000000000000000'
      },
      requestBody: '{"method":"eth_estimateGas","params":[{"type":"0x2","maxFeePerGas":"0xbfda3a300","maxPriorityFeePerGas":"0x59682f00","from":"0x873784c8a011a32c7635c8d8d3d2c83060532a49","to":"0xc249632c2d40b9001fe907806902f63038b737ab","data":"0x26ef699d000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000c0000000000000000000000000000000000000000000000000000000000000012000000000000000000000000000000000000000000000000000000000004c4b4000000000000000000000000000000000000000000000000000000000000000096f736d6f7369732d370000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002b6f736d6f31657539796c383776346537326473636c32353635706e666e646577356a363865367a3965323400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000067561757364630000000000000000000000000000000000000000000000000000"}],"id":76,"jsonrpc":"2.0"}',
      requestMethod: 'POST',
      url: 'https://api.avax-test.network/ext/bc/C/rpc'
    }
  },
  tx: {
    to: Promise { '0xC249632c2D40b9001FE907806902f63038B737Ab' },
    data: '0x26ef699d000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000c0000000000000000000000000000000000000000000000000000000000000012000000000000000000000000000000000000000000000000000000000004c4b4000000000000000000000000000000000000000000000000000000000000000096f736d6f7369732d370000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002b6f736d6f31657539796c383776346537326473636c32353635706e666e646577356a363865367a3965323400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000067561757364630000000000000000000000000000000000000000000000000000',
    value: undefined,
    from: '0x873784c8A011A32C7635C8d8D3D2c83060532A49',
    type: 2,
    maxFeePerGas: BigNumber { _hex: '0x0bfda3a300', _isBigNumber: true },
    maxPriorityFeePerGas: BigNumber { _hex: '0x59682f00', _isBigNumber: true },
    nonce: Promise { 31 },
    gasLimit: Promise { <rejected> [Circular *1] },
    chainId: Promise { 43113 }
  }
}

Node.js v18.20.1
```

#### 2. Transaction reverted
On manually specifying the `gasLimit` and running the code:
  - `txOptions: { gasLimit: "700000" },`

This is the transaction that is formed:

```
adwait@vivobook-m1603qa:~/projects/axelar/axelar-experiments$ node evmTransfer.js 
{
type: 2,
  chainId: 43113,
  nonce: 32,
  maxPriorityFeePerGas: BigNumber { _hex: '0x59682f00', _isBigNumber: true },
  maxFeePerGas: BigNumber { _hex: '0x0bfda3a300', _isBigNumber: true },
  gasPrice: null,
  gasLimit: BigNumber { _hex: '0x4c4b40', _isBigNumber: true },
  to: '0xC249632c2D40b9001FE907806902f63038B737Ab',
  value: BigNumber { _hex: '0x00', _isBigNumber: true },
  data: '0x26ef699d000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000c0000000000000000000000000000000000000000000000000000000000000012000000000000000000000000000000000000000000000000000000000004c4b4000000000000000000000000000000000000000000000000000000000000000096f736d6f7369732d370000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002b6f736d6f31657539796c383776346537326473636c32353635706e666e646577356a363865367a3965323400000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000067561757364630000000000000000000000000000000000000000000000000000',
  accessList: [],
  hash: '0x1bdb9edb32200c908c8eec6c79a00504544f035844fa83d141c99064a98b2515',
  v: 0,
  r: '0x0d3e974b5866c0b778767b4a7e814144a88af9c6ee1c4d369135d9e6251cf316',
  s: '0x13f6c0e6bfbf80bea2523aa0265a6bca54a17424d1e696746a1e21ce51d8f258',
  from: '0x873784c8A011A32C7635C8d8D3D2c83060532A49',
  confirmations: 0,
  wait: [Function (anonymous)]
}
```

On Snowtrace, the [transaction](https://testnet.snowtrace.io/tx/0x1bdb9edb32200c908c8eec6c79a00504544f035844fa83d141c99064a98b2515?chainId=43113) seems to have failed.

The `Input Data` field shows a `sendToken` method call to the [contract](https://testnet.snowtrace.io/address/0xC249632c2D40b9001FE907806902f63038B737Ab)

Looking at the [code for the contract](https://testnet.snowtrace.io/address/0xC249632c2D40b9001FE907806902f63038B737Ab/contract/43113/code), I am unable to find an instance of the `sendToken` method.

**Comment by Adw8** [comment]
Figured out what was going wrong. I didn't have the `aUSDC` tokens in my wallet, Getting the tokens from the faucet in the Axelar discord solved this issue.
